// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using net6codefirstmigration;

#nullable disable

namespace net6codefirstmigration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("net6codefirstmigration.Entidad.Genero", b =>
                {
                    b.Property<int>("intPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("intPk"), 1L, 1);

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("intPk");

                    b.ToTable("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
